name: clinical_warehouse
version: "1.0.0"
config-version: 2
profile: clinical_warehouse

model-paths: ["models"]
macro-paths:  ["macros"]
test-paths:   ["tests"]

models:
  clinical_warehouse:
    staging:
      +schema:       SILVER_STAGING
      +materialized: view
    marts:
       +schema:       GOLD
       +materialized: table
     
